[package]
cairo-version = "2.4.0"
name = "autochessia"
version = "0.0.1"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.6.0" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]

# development
# Default account for katana with seed = 0
rpc_url = "http://localhost:5050/"
account_address = "0x6162896d1d7ab204c7ccac6dd5f8e9e7c25ecd5ae4fcb4ad32e57786bb46e03"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
world_address = "0x645cb3e9b4d7ae1afd34d64085e61519e431c39d4811f4e6bbc5f16b66fb0"

# cartridge slot
# rpc_url = "https://api.cartridge.gg/x/autochessia/katana"
# account_address = "0x63da8dd5256712ad603d66ff58e05633ae71b7861f5f8e0bd776f3d4b927d2f"
# private_key = ""


[tool.dojo.world]
name = "autochessia"
description = "auto chess battle game"
# icon_uri = "file://assets/icon.png"
# cover_uri = "file://assets/cover.png"
socials.x = "https://twitter.com/auto_chessia"
